
sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t maleckicoa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maleckicoa/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-us-west-2-026803142645'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id:  $AWS_ELASTICBEANSTALK_ACESS_KEY
  secret_access_key:  $AWS_ELASTICBEANSTALK_SECRET_KEY
