sudo: required
language: generic 
services:
  -docker
before install:
  -docker build -t maleckicoa/docker-react -f Dockerfile.dev .

script:
#  -docker run  maleckicoa/docker-react npm run test -- --coverage
 - docker run -e CI=true maleckicoa/docker-react npm run test
