sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t maleckicoa/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true maleckicoa/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west"
  app: "docker-react"
  env: "	DockerReact-env" # starting up elasticbeanstock creates an environment
  bucket_name: "elasticbeanstalk-us-west-2-026803142645" # same s3 bucket is reused for all elasticbeanstock environments
  bucket_path: "docker-react" # specify the folder inside s3 bucket for this specific environment
  on:
    branch: master # deployment only when new commit to master branch
  access_key_id: $AWS_ELASTICBEANSTALK_ACCESS_KEY
  secret_access_key: $AWS_ELASTICBEANSTALK_SECRET_KEY
